// CopyRight
const CW_FOOTER = "2023 Mohammad Ghareb";
const CW_NAVBAR_TITLE = "Book Management System";
const CW_NAVBAR_LOGOUT = "Logout";

const CW_LOGIN_TITLE = "Login to Dashboard";
const CW_LOGIN_EMAIL = "Email";
const CW_LOGIN_PASSWORD = "Password";
const CW_LOGIN_SIGNIN = "Sign In";
const CW_LOGIN_RESET = "Reset";
const CW_SEARCH_BY_AUTHOR = "Search by author";
const CW_SEARCH_BY_TITLE = "Search by title";
const CW_MANAGE_BOOKS = "Manage Books";
const CW_ADD_BOOK = "ADD";
const CW_BACK_LOGIN = "Back to Login";
const CW_RESET_PASSWORD_TITLE = "Reset Password by Email";
const CW_RESET_PASSWORD_SEND_EMAIL = "Submit";
const CW_REGISTER_AUTHOR_BIO = "Author Bio";

const CW_REGISTER_BIRTHDATE = "BirthDate";

const CW_REGISTER_PASSWORD = "Password";
const CW_REGISTER_EMAIL = "E-mail Address";
const CW_REGISTER_NAME = "Full Name";
const CW_REGISTER_TITLE = "Register";
const CW_REGISTER_SUBMIT = "Register";
const CW_REGISTER_ALREADY = " Already have an account?";
const CW_LOGIN_DONT = " Don't have an account?";
const CW_LOGIN_FORGET = "Forgot Password";
const CW_EDIT_TITLE = "Updating book...";
const CW_EDIT_COVER_IMAGE = "Cover Image";
const CW_EDIT_BOOK = "Edit Book";
const CW_EDIT_BACK_DASHBOARD = "Back to dashboard";
const CW_EDIT_BUTTON_TITLE = "Title";
const CW_EDIT_BUTTON_AUTHOR = "Author";
const CW_EDIT_BUTTON_DATE = "Date Published";
const CW_EDIT_BUTTON_BRIEF = "Brief";
const CW_EDIT_BUTTON_COVER_IMAGE = "Upload Cover Image";
const CW_EDIT_BUTTON_UPDATE_BOOK = "Update Book";
const CW_EDIT_BUTTON_CANCEL = "Cancel";
const CW_DASHBOARD_VIEW_DETAILS = "View Details";
const CW_DASHBOARD_NO_BOOKS_AVAILABLE = "No Books Available";
const CW_ADD_BOOK_NEW = "Add New Book";
const CW_ADD_BOOK_BACK = "Back to dashboard";
const CW_ADD_BUTTON_COVER_IMAGE = "Cover Image";
const CW_ADD_BUTTON_TITLE = "Title";
const CW_ADD_BUTTON_AUTHOR = "Author";
const CW_ADD_BUTTON_DATE = "Date Published";
const CW_ADD_BUTTON_BRIEF = "Brief";
const CW_ADD_BUTTON_UPLOAD_COVER_IMAGE = "Upload Cover Image";
const CW_ADD_BUTTON_ADD_BOOK = "Add Book";
const CW_ADD_BUTTON_RESET = "Reset";
const CW_DETAILS_BACK = "Back to dashboard";

const CW_DETAILS_TITLE = "Title:";
const CW_DETAILS_AUTHOR = "Author:";
const CW_DETAILS_DATE = "Date:";
const CW_DETAILS_BRIEF = "Brief:";
const CW_DETAILS_PAGE_TITLE = "Details";
const CW_DETAILS_EDIT = "Edit";
const CW_DETAILS_DELETE = "Delete";
export {
  CW_FOOTER,
  CW_NAVBAR_TITLE,
  CW_LOGIN_TITLE,
  CW_LOGIN_EMAIL,
  CW_LOGIN_PASSWORD,
  CW_LOGIN_SIGNIN,
  CW_LOGIN_RESET,
  CW_SEARCH_BY_AUTHOR,
  CW_SEARCH_BY_TITLE,
  CW_MANAGE_BOOKS,
  CW_ADD_BOOK,
  CW_BACK_LOGIN,
  CW_RESET_PASSWORD_TITLE,
  CW_RESET_PASSWORD_SEND_EMAIL,
  CW_REGISTER_AUTHOR_BIO,
  CW_REGISTER_BIRTHDATE,
  CW_REGISTER_PASSWORD,
  CW_REGISTER_EMAIL,
  CW_REGISTER_NAME,
  CW_REGISTER_TITLE,
  CW_NAVBAR_LOGOUT,
  CW_REGISTER_SUBMIT,
  CW_REGISTER_ALREADY,
  CW_LOGIN_DONT,
  CW_LOGIN_FORGET,
  CW_EDIT_TITLE,
  CW_EDIT_COVER_IMAGE,
  CW_EDIT_BOOK,
  CW_EDIT_BACK_DASHBOARD,
  CW_EDIT_BUTTON_TITLE,
  CW_EDIT_BUTTON_AUTHOR,
  CW_EDIT_BUTTON_DATE,
  CW_EDIT_BUTTON_BRIEF,
  CW_EDIT_BUTTON_COVER_IMAGE,
  CW_EDIT_BUTTON_UPDATE_BOOK,
  CW_EDIT_BUTTON_CANCEL,
  CW_DASHBOARD_VIEW_DETAILS,
  CW_DASHBOARD_NO_BOOKS_AVAILABLE,
  CW_ADD_BOOK_NEW,
  CW_ADD_BOOK_BACK,
  CW_ADD_BUTTON_COVER_IMAGE,
  CW_ADD_BUTTON_TITLE,
  CW_ADD_BUTTON_AUTHOR,
  CW_ADD_BUTTON_DATE,
  CW_ADD_BUTTON_BRIEF,
  CW_ADD_BUTTON_UPLOAD_COVER_IMAGE,
  CW_ADD_BUTTON_ADD_BOOK,
  CW_ADD_BUTTON_RESET,
  CW_DETAILS_BACK,
  CW_DETAILS_TITLE,
  CW_DETAILS_AUTHOR,
  CW_DETAILS_DATE,
  CW_DETAILS_BRIEF,
  CW_DETAILS_PAGE_TITLE,
  CW_DETAILS_EDIT,
  CW_DETAILS_DELETE,
};
